<?php

namespace Gpupo\CommonSchema\ORM\Repository\Trading\Order;

/**
 * OrderStatusDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatusDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
