<?php

namespace Gpupo\CommonSchema\ORM\Repository\Trading\Order\Shippings\Products;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
}
