# expands gpupo/common-schema
# version: 2.0
# generated at Fri, 25 May 2018 17:40:13 +0000
Gpupo\CommonSchema\Entity\Trading\Order\Order:
    type: entity
    table: Gpupo\CommonSchema\Entity\Trading\Order\Order
    repositoryClass: Gpupo\CommonSchema\Entity\Trading\Order\OrderRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        order_number:
            type: string
        order_status:
            type: string
        order_status_detail:
            type: object
        order_type:
            type: string
        date_created:
            type: datetime
        date_closed:
            type: datetime
        date_agreed:
            type: datetime
        date_last_modified:
            type: datetime
        origin_business_unit:
            type: string
        origin_number:
            type: string
        origin_site:
            type: string
        currency_id:
            type: string
        total_commission:
            type: number
        total_discount:
            type: number
        total_freight:
            type: number
        total_gross:
            type: number
        total_net:
            type: number
        total_quantity:
            type: number
        shippings:
            type: object
        customer:
            type: object
        payments:
            type: object
        feedback:
            type: object
        requested_devolution:
            type: boolean
        requested_exchange:
            type: boolean
        tags:
            type: array
        expands:
            type: array
