<?php

namespace Gpupo\CommonSchema\ORM\Repository\Trading\Order\Customer;

/**
 * AddressDeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressDeliveryRepository extends \Doctrine\ORM\EntityRepository
{
}
