<?php

namespace Gpupo\CommonSchema\ORM\Repository\Trading\Order\Customer;

/**
 * AddressBillingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressBillingRepository extends \Doctrine\ORM\EntityRepository
{
}
