<?php

namespace Gpupo\CommonSchema\ORM\Repository\Trading\Payment;

/**
 * AtmTransferReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtmTransferReferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
