<?php

namespace Gpupo\CommonSchema\ORM\Repository\Trading\Order\Shippings\Transport;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
}
