<?php

namespace Gpupo\CommonSchema\ORM\Repository\Trading\Payment\Collector;

/**
 * CollectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectorRepository extends \Doctrine\ORM\EntityRepository
{
}
