<?php

namespace Gpupo\CommonSchema\ORM\Repository\Trading;

/**
 * TradingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradingRepository extends \Doctrine\ORM\EntityRepository
{
}
