<?php

declare(strict_types=1);

/*
 * This file is part of gpupo/common-schema created by Gilmar Pupo <contact@gpupo.com>
 * For the information of copyright and license you should read the file LICENSE which is
 * distributed with this source code. For more information, see <https://opensource.gpupo.com/>
 */

namespace Gpupo\CommonSchema\ORM\EntityRepository\Banking\Movement;

use Gpupo\CommonSchema\ORM\Entity\EntityInterface;

/**
 * MovementRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovementRepository extends \Gpupo\CommonSchema\ORM\EntityRepository\AbstractEntityRepository
{
    protected function defaultFindByParameters(EntityInterface $entity): array
    {
        return ['move_id' => $entity->getMoveId()];
    }
}
